#!/usr/bin/env python3
"""
Converts Byte_AI.png into a full-color ANSI ASCII-art banner using classic
brightness-mapped characters (a ramp from sparse/blank for dark pixels to
dense "@"/"#"/"%" for bright ones, each colored via truecolor foreground
escapes from the source pixel), then emits it as a C++ header with the
banner baked in as a raw string literal, printed by /version.

Usage:
    ./generate_logo_ascii.py [width_in_columns]
"""
import sys
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
SRC_PNG = ROOT / "Byte_AI.png"
OUT_HEADER = ROOT / "modules" / "logo_banner.h"

WIDTH = int(sys.argv[1]) if len(sys.argv) > 1 else 48

# sparsest (dark) to densest (bright)
RAMP = " .:-=+*#%@"


def build_banner(width: int) -> str:
    img = Image.open(SRC_PNG).convert("RGB")

    # terminal character cells are roughly twice as tall as wide, so sample
    # fewer rows than columns to keep the aspect ratio looking right
    aspect = img.height / img.width
    height = max(1, round(width * aspect / 2))

    small = img.resize((width, height), Image.LANCZOS)
    px = small.load()

    lines = []
    for y in range(height):
        line = []
        for x in range(width):
            r, g, b = px[x, y]
            brightness = (0.299 * r + 0.587 * g + 0.114 * b) / 255.0
            ch = RAMP[min(len(RAMP) - 1, int(brightness * len(RAMP)))]
            if ch == " ":
                line.append(" ")
            else:
                line.append(f"\\033[38;2;{r};{g};{b}m{ch}")
        lines.append("".join(line) + "\\033[0m")
    return "\\n".join(lines)


def main() -> None:
    banner = build_banner(WIDTH)

    OUT_HEADER.write_text(
        "#pragma once\n\n"
        "// auto-generated by scripts/generate_logo_ascii.py from Byte_AI.png -- do not hand-edit\n"
        "static const char * BYTE_LOGO_BANNER =\n"
        f"    \"{banner}\\n\";\n"
    )
    print(f"wrote {OUT_HEADER.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
