#!/usr/bin/env python3
"""
Converts Byte_AI.png into a full-color ANSI truecolor ASCII-art banner using
half-block characters (each terminal cell encodes two source pixels: a
foreground-colored top half and background-colored bottom half via the U+2580
"upper half block" character), then emits it as a C++ header with the banner
baked in as a raw string literal, printed by /version.

Usage:
    ./generate_logo_ascii.py [width_in_columns]
"""
import sys
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
SRC_PNG = ROOT / "Byte_AI.png"
OUT_HEADER = ROOT / "modules" / "logo_banner.h"

WIDTH = int(sys.argv[1]) if len(sys.argv) > 1 else 32


def build_banner(width: int) -> str:
    img = Image.open(SRC_PNG).convert("RGB")

    # each output row uses 2 source pixel-rows (half-block trick), so sample
    # at double vertical resolution relative to the character grid
    aspect = img.height / img.width
    height = max(1, round(width * aspect / 2))  # /2: terminal chars are ~2x tall as wide

    img = img.resize((width, height * 2))
    px = img.load()

    lines = []
    for y in range(0, height * 2, 2):
        line = []
        for x in range(width):
            top = px[x, y]
            bot = px[x, y + 1] if y + 1 < height * 2 else top
            line.append(f"\\033[38;2;{top[0]};{top[1]};{top[2]}m\\033[48;2;{bot[0]};{bot[1]};{bot[2]}m▀")
        lines.append("".join(line) + "\\033[0m")
    return "\\n".join(lines)


def main() -> None:
    banner = build_banner(WIDTH)

    OUT_HEADER.write_text(
        "#pragma once\n\n"
        "// auto-generated by scripts/generate_logo_ascii.py from Byte_AI.png -- do not hand-edit\n"
        "static const char * BYTE_LOGO_BANNER =\n"
        f"    \"{banner}\\n\";\n"
    )
    print(f"wrote {OUT_HEADER.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
